[helpers]

[default]
depends = []

[ideavim.files]
".ideavimrc" = "~/.ideavimrc"

[pwsh.files]
"Microsoft.PowerShell_profile.ps1" = "~/.config/powershell/profile.ps1"

[bash.files]
"bash/.bashrc" = "~/.bashrc"
"bash/bash" = "~/.config/bash"

[nvim.files]
"nvim" = "~/.config/nvim"

[wezterm.files]
"wezterm" = "~/.config/wezterm"
